### ISSUE TITLE
Supabase CLI fails to link

### ISSUE THREAD

**Issue by bericyb** [supabase/supabase-action-example#18]
# Bug report

## Describe the bug

The current examples of workflows use CLI version 1.0.0 which does not work with the latest Postgres 15 migration 

## To Reproduce

1. Trigger Github action with Supabase CLI version 1.0.0
2. Follow the CLI command `supabase link`
3. See error. 

## Expected behavior

Supabase CLI has no errors with Postrgres 15 when linking 

## Screenshots

![Screenshot 2023-01-18 at 09 28 28](https://user-images.githubusercontent.com/37596980/213236471-13e87f6d-513e-4472-91e1-f6cb0f9946f7.png)

## System information

- OS: ubuntu-latest

## Additional context

Related to this issue [here] (https://github.com/supabase/cli/issues/756)

**Comment by trevorhuis-bithuis** [comment]
Facing the same error on 'supabase start'
<img width="555" alt="image" src="https://user-images.githubusercontent.com/104961638/213721719-06ca635c-1f2e-4f1f-ad3d-d4871ec24d0c.png">
